export const GET_ALL_BREEDS = "GET_ALL_BREEDS";
export const GET_DOGS_IMAGES_BY_BREED = "GET_DOGS_IMAGES_BY_BREED";
export const SET_LOADING = "SET_LOADING";
export const SET_ACTIVE_STATE = "SET_ACTIVE_STATE";
export const SET_SELECTED_BREED = "SET_SELECTED_BREED";
export const CLEAR_DOGS_IMAGES = "CLEAR_DOGS_IMAGES";
